### PR TITLE
NGSTACK-314 add filter options

### PR DESCRIPTION
**Pull request by iherak**
This PR adds:
* filtering by subtree
* filtering by created/modified date
* filtering by owner
* links in context menu to class list
* basic statistics for classes under selected subtree

### CODE REVIEW

**Comment by ivrdoljak** [comment]
Links in the "Content in subtree by class" section should preserve the subtree filter. Currently, the subtree filter is lost when a link here is selected.

list_by_content_type

**Comment by iherak** [comment]
@ivrdoljak added in cdff08aa4ae8f665549fa73ce41e33266029bfc8

**Comment by iherak** [comment]
Added information about hidden nodes in 0db388f
cc @ivrdoljak

**Comment by iherak** [comment]
@ivrdoljak can we merge this?

**Comment by iherak** [comment]
all remarks have been addressed, @ivrdoljak confirm if we can merge.

**Comment by emodric** [comment]
Thanks everyone!

**Comment by emodric** [comment]
Released as 2.1.0.

**Pull request merged**
